# Unable to generate docker-compose script by copilot
version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "distributed_library_service"
    restart: always
#    networks:
#      - app-network
#
#  app:
#    build: .
#    container_name: distributed-library-service
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mysql
#    networks:
#      - app-network
#
#networks:
#  app-network:
#    driver: bridge
